# Generated by Django 2.2.12 on 2020-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phoneno', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
