# Generated by Django 2.2.12 on 2020-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0004_auto_20200422_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_pic',
        ),
    ]
