# Generated by Django 2.2.12 on 2020-04-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0006_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
