# Generated by Django 2.2.12 on 2020-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0008_auto_20200422_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
