# Generated by Django 2.2.12 on 2020-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0010_auto_20200424_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
