# Generated by Django 2.2.12 on 2020-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0014_auto_20200428_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
