# Generated by Django 2.2.12 on 2020-05-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0015_auto_20200430_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
