# Generated by Django 2.2.12 on 2020-05-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0016_auto_20200501_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('requirement', models.TextField()),
                ('description', models.TextField()),
                ('code_file', models.FileField(upload_to='code/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_video', models.FileField(upload_to='videos/')),
                ('featured', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InnovzaApp.UserInfo')),
                ('categories', models.ManyToManyField(to='InnovzaApp.Category')),
            ],
        ),
    ]
