# Generated by Django 2.2.12 on 2020-05-01 17:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0017_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirement',
            field=tinymce.models.HTMLField(),
        ),
    ]
