# Generated by Django 2.2.12 on 2020-05-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0018_auto_20200501_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='InnovzaApp.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InnovzaApp.UserInfo')),
            ],
        ),
    ]
