# Generated by Django 2.2.12 on 2020-05-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0021_auto_20200502_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InnovzaApp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InnovzaApp.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_comments', to='InnovzaApp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InnovzaApp.UserInfo')),
            ],
        ),
    ]
