# Generated by Django 3.0.6 on 2020-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovzaApp', '0022_auto_20200502_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
